### ISSUE TITLE
Doesn't handle OS X

### ISSUE THREAD

**Issue by stephenreay** [Alliants/mapular#1]
Mac OS X has had Maps.app since late 2013 - your UA check only targets iOS devices.

**Comment by yatryan** [comment]
The [demo](https://alliants.github.io/mapular/#/demo) works on Mac, pointing to Google Maps. Would we want to open another app from a web page, or just stay in browser and link to Google Maps?

**Comment by stephenreay** [comment]
If you’re providing “open a map" functionality, I would expect it to use what’s available for the platform.

I don’t actually use this lib (just came here from a linked article on HN) - My approach for a client is to give _all_ clients a link to the apple service, as they automatically redirect to google maps if it doesn’t detect a device with maps.app

**Comment by yatryan** [comment]
Ah ok, that makes sense.

**Comment by samward** [comment]
@stephenreay I took a look at adding an option for the behaviour you described but it added quite a bit of complexity. I don't think many users or developers will utilise it as it may be quite jarring for a desktop user to be removed from their browser during a session.
